on:
 push:
   branches:
   - main

env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 

jobs:
 terraform:
   name: "Terraform Deployment"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
   steps:
     - name: Checkout
       uses: actions/checkout@v5