on:
 push:
   branches:
   - main

env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 

jobs:
  terraform:
    name: "Terraform Deployment"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - name: Terraform format
        id: fmt
        run: terraform fmt -check

